# Stage 1: Build
FROM node:20-alpine as build

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

# Modificar para usar una variable de entorno en tiempo de ejecución
RUN sed -i "s|http://localhost:8080|${BACKEND_URL:-http://localhost:8080}|g" src/environments/environment.prod.ts

RUN npm run build

# Stage 2: Serve
FROM nginx:alpine

# Copiar la aplicación construida
COPY --from=build /app/dist/front-list-items/browser /usr/share/nginx/html

# Copiar un script para reemplazar las variables de entorno en tiempo de ejecución
COPY docker-entrypoint.sh /docker-entrypoint.sh
RUN chmod +x /docker-entrypoint.sh

# Copiar la configuración de nginx
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

# Usar el script como punto de entrada
ENTRYPOINT ["/docker-entrypoint.sh"]
CMD ["nginx", "-g", "daemon off;"]
