# Stage 1: Build
FROM node:20-alpine as build

WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .

# Script para reemplazar la variable de entorno
RUN echo "console.log(process.env.BACKEND_URL || 'http://localhost:8080');" > env.js
RUN echo "const fs = require('fs');" >> env.js
RUN echo "const environmentFile = 'src/environments/environment.prod.ts';" >> env.js
RUN echo "let content = fs.readFileSync(environmentFile, 'utf8');" >> env.js
RUN echo "content = content.replace('\${BACKEND_URL}', process.env.BACKEND_URL || 'http://localhost:8080');" >> env.js
RUN echo "fs.writeFileSync(environmentFile, content);" >> env.js

# Ejecutar el script y construir
RUN node env.js && npm run build

# Stage 2: Serve
FROM nginx:alpine
COPY --from=build /app/dist/front-list-items/browser /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
